/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sieteymedia;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author dav
 */
public class Banca1 extends javax.swing.JDialog {
    boolean daw = true;
    int contador = 0;
    float puntuacion;
    boolean interruptor;
    int auxiliar;
    float puntos;
    private Baraja baraja;
    Hilo1 hilo;
    boolean sw;
    /**
     * Creates new form Banca1
     * @param parent
     * @param modal
     * @param puntuacion
     * @param baraja
     */
    public Banca1(java.awt.Frame parent, boolean modal, float puntuacion, Baraja baraja) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.puntuacion = puntuacion;
        interruptor = true;
        auxiliar = 0;
        puntos = 0;
        this.baraja = baraja;
        hilo = new Hilo1();
        carta1.setVisible(false);
        carta2.setVisible(false);
        carta3.setVisible(false);
        carta4.setVisible(false);
        carta5.setVisible(false);
        carta6.setVisible(false);
        carta7.setVisible(false);
        carta8.setVisible(false);
        carta9.setVisible(false);
        carta10.setVisible(false);
        carta11.setVisible(false);
        carta12.setVisible(false);
        carta13.setVisible(false);
        carta14.setVisible(false);
        marcador.setText("Tu puntuacion: "+puntuacion);
        sw = true;
        marcador1.setText("Jugador 2: 0 ptos");
        this.setTitle("Juega Jugador 2");
        
    }

    private Banca1(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marcador = new javax.swing.JLabel();
        marcador1 = new javax.swing.JLabel();
        carta14 = new javax.swing.JLabel();
        carta13 = new javax.swing.JLabel();
        carta12 = new javax.swing.JLabel();
        carta11 = new javax.swing.JLabel();
        carta10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        carta9 = new javax.swing.JLabel();
        carta8 = new javax.swing.JLabel();
        carta7 = new javax.swing.JLabel();
        carta6 = new javax.swing.JLabel();
        carta5 = new javax.swing.JLabel();
        carta4 = new javax.swing.JLabel();
        carta3 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        tapete = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marcador.setBackground(new java.awt.Color(175, 167, 160));
        marcador.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        marcador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcador.setText("Puntacion: 0 ");
        marcador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(249, 252, 16)));
        marcador.setFocusable(false);
        marcador.setOpaque(true);
        getContentPane().add(marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 240, 50));

        marcador1.setBackground(new java.awt.Color(175, 167, 160));
        marcador1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        marcador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcador1.setText("Puntacion: 0 ");
        marcador1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(249, 252, 16)));
        marcador1.setFocusable(false);
        marcador1.setOpaque(true);
        getContentPane().add(marcador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 270, 50));

        carta14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, 230));

        carta13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 230));

        carta12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, 230));

        carta11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 230));

        carta10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 230));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 245, 245));
        jLabel1.setText("Jugador 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 50));

        carta9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, 230));

        carta8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 230));

        carta7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 230));

        carta6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 230));

        carta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 230));

        carta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 230));

        carta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 230));

        carta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 230));

        carta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 230));

        tapete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.jpg"))); // NOI18N
        getContentPane().add(tapete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 780, 390));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marron.jpg"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(800, 600));
        fondo.setMinimumSize(new java.awt.Dimension(800, 600));
        fondo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(daw)
        {
            hilo.start();
            daw = false;
        }    
    }//GEN-LAST:event_formWindowActivated

        public void jugar()
    {
        if(puntuacion<=puntos)
        {
            
            interruptor=false;
        }
    }
        
    public void sacarCarta()
    {
        if(puntuacion<=puntos)
                {
                    interruptor = false;
                    Banca1.this.dispose();
                    
                }
        
        int palo, numero;
        contador++;
        //Saca una carta aleatoria y comprueba si ya ha salido
        do
        {
            palo = (int)(Math.random()*4);
            numero = (int)(Math.random()*10)+1;
        }while(!baraja.comprobarCarta(palo ,numero));
        
        baraja.sacarCarta(palo, numero);
        
        puntos = puntos + baraja.valorCarta(numero);
        if(sw)
        {
            if(puntuacion<=puntos)
            {
                sw=false;
            }
            baraja.setpuntosB(puntos);
        }
        marcador1.setText("Jugador 2: "+baraja.getPuntosB()+" ptos");
        
        String carta = String.valueOf(numero);
        String resultado = "/imagenes/"+palo+"y"+carta+".png";
        
                switch(contador)
                {
                    
                    case 1: 
                    carta1.setVisible(true);    
                    carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 2: 
                    carta2.setVisible(true);      
                    carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 3: 
                    carta3.setVisible(true);      
                    carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 4: 
                    carta4.setVisible(true);      
                    carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 5: 
                    carta5.setVisible(true);      
                    carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 6:
                    carta6.setVisible(true);      
                    carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 7:
                    carta7.setVisible(true);      
                    carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 8:
                    carta8.setVisible(true);      
                    carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 9:
                    carta9.setVisible(true);      
                    carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 10:
                    carta10.setVisible(true);      
                    carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 11:
                    carta11.setVisible(true);      
                    carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 12:
                    carta12.setVisible(true);      
                    carta12.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 13:
                    carta13.setVisible(true);      
                    carta13.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 14:
                    carta14.setVisible(true);      
                    carta14.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    default: 
                    carta1.setVisible(true);      
                    carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trasera.png")));
                    break;
                }
                
                        
    }
    /**    
   
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Banca1 dialog;
            dialog = new Banca1(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    
    //Crea un hilo de ejecucion que saca cartas cada 2.5 segundos
    private class Hilo1 extends Thread
    {
    @Override
    public void run()
            {
        try {
            while(interruptor)
            {
                
                switch(auxiliar)
                {
                    case 0:
                        break;
                    case 20:
                        sacarCarta();
                        break;
                    case 40:
                        sacarCarta();
                        break;
                    case 60:
                        sacarCarta();
                        break;
                    case 80:
                        sacarCarta();
                        break;
                    case 100:
                        sacarCarta();
                        break;
                    case 120:
                        sacarCarta();
                        break;
                    case 140:
                        sacarCarta();
                        break;
                    case 160:
                        sacarCarta();
                        break;
                    case 180:
                        sacarCarta();
                        break;
                    case 200:
                        sacarCarta();
                        break;
                    case 220:
                        sacarCarta();
                        break;
                    case 240:
                        sacarCarta();
                        break;
                    case 260:
                        sacarCarta();
                        break;
                    case 280:
                        sacarCarta();
                        break;    
                    case 300:
                       interruptor=false;
                        break;
                }
                auxiliar++;
                
            Thread.sleep(100);}
            Banca1.this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta10;
    private javax.swing.JLabel carta11;
    private javax.swing.JLabel carta12;
    private javax.swing.JLabel carta13;
    private javax.swing.JLabel carta14;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel carta3;
    private javax.swing.JLabel carta4;
    private javax.swing.JLabel carta5;
    private javax.swing.JLabel carta6;
    private javax.swing.JLabel carta7;
    private javax.swing.JLabel carta8;
    private javax.swing.JLabel carta9;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel marcador;
    private javax.swing.JLabel marcador1;
    private javax.swing.JLabel tapete;
    // End of variables declaration//GEN-END:variables
}
