/*
 * Clase que cargar la ventan principal y el juego principal
 */
package sieteymedia;

//import java.util.logging.Level;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//import java.util.logging.Logger;

/**
 *
 * @author dav
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    int contador;
    Baraja baraja;
    float puntuacion;
    boolean sw;
    int auxiliar;
//    Hilo1 hilo;
    Banca1 banca;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        baraja = new Baraja();
        iniciarPartida();
        sw=true;
        auxiliar = 0;
//        hilo = new Hilo1();
        escriturahistorico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pto5 = new javax.swing.JTextArea();
        pto4 = new javax.swing.JTextArea();
        pto3 = new javax.swing.JTextArea();
        pto2 = new javax.swing.JTextArea();
        pto1 = new javax.swing.JTextArea();
        salida1 = new javax.swing.JTextArea();
        carta14 = new javax.swing.JLabel();
        carta13 = new javax.swing.JLabel();
        carta12 = new javax.swing.JLabel();
        carta11 = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        carta10 = new javax.swing.JLabel();
        carta9 = new javax.swing.JLabel();
        carta8 = new javax.swing.JLabel();
        carta7 = new javax.swing.JLabel();
        carta6 = new javax.swing.JLabel();
        oportunidad = new javax.swing.JLabel();
        carta5 = new javax.swing.JLabel();
        carta4 = new javax.swing.JLabel();
        carta3 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        reiniciar = new javax.swing.JButton();
        tapete = new javax.swing.JLabel();
        historico = new javax.swing.JTextArea();
        sacar = new javax.swing.JButton();
        marcador = new javax.swing.JLabel();
        plantar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSacar = new javax.swing.JMenuItem();
        menuMePlanto = new javax.swing.JMenuItem();
        menuReiniciar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();
        instrucciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siete y Media");
        setBackground(new java.awt.Color(204, 121, 38));
        setForeground(java.awt.Color.lightGray);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoies.png")).getImage());
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pto5.setEditable(false);
        pto5.setBackground(new java.awt.Color(178, 178, 178));
        pto5.setColumns(20);
        pto5.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        pto5.setForeground(new java.awt.Color(243, 243, 237));
        pto5.setRows(5);
        pto5.setText("  5");
        pto5.setOpaque(false);
        getContentPane().add(pto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 40, 70));

        pto4.setEditable(false);
        pto4.setBackground(new java.awt.Color(178, 178, 178));
        pto4.setColumns(20);
        pto4.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        pto4.setForeground(new java.awt.Color(243, 243, 237));
        pto4.setRows(5);
        pto4.setText("  4");
        pto4.setOpaque(false);
        getContentPane().add(pto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 40, 70));

        pto3.setEditable(false);
        pto3.setBackground(new java.awt.Color(178, 178, 178));
        pto3.setColumns(20);
        pto3.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        pto3.setForeground(new java.awt.Color(243, 243, 237));
        pto3.setRows(5);
        pto3.setText("  3 ");
        pto3.setOpaque(false);
        getContentPane().add(pto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 40, 70));

        pto2.setEditable(false);
        pto2.setBackground(new java.awt.Color(178, 178, 178));
        pto2.setColumns(20);
        pto2.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        pto2.setForeground(new java.awt.Color(243, 243, 237));
        pto2.setRows(5);
        pto2.setText("  2");
        pto2.setOpaque(false);
        getContentPane().add(pto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, 70));

        pto1.setEditable(false);
        pto1.setBackground(new java.awt.Color(178, 178, 178));
        pto1.setColumns(20);
        pto1.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        pto1.setForeground(new java.awt.Color(243, 243, 237));
        pto1.setRows(5);
        pto1.setText("   1 ");
        pto1.setOpaque(false);
        getContentPane().add(pto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 40, 70));

        salida1.setEditable(false);
        salida1.setBackground(new java.awt.Color(178, 178, 178));
        salida1.setColumns(20);
        salida1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        salida1.setForeground(new java.awt.Color(240, 27, 27));
        salida1.setRows(5);
        salida1.setOpaque(false);
        getContentPane().add(salida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 350, 90));

        carta14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, 230));

        carta13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 230));

        carta12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, 230));

        carta11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 230));

        salida.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        salida.setForeground(new java.awt.Color(241, 14, 14));
        salida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salida.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 370, 130));

        carta10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 230));

        carta9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, 230));

        carta8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, 230));

        carta7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 230));

        carta6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 230));

        oportunidad.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        oportunidad.setForeground(new java.awt.Color(241, 14, 14));
        oportunidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(oportunidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 370, 50));

        carta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 230));

        carta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 230));

        carta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, 230));

        carta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 230));

        carta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traseraCarta.png"))); // NOI18N
        getContentPane().add(carta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 230));

        reiniciar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        reiniciar.setText("Reiniciar partida");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 180, 40));

        tapete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/verde.jpg"))); // NOI18N
        getContentPane().add(tapete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 880, 380));

        historico.setEditable(false);
        historico.setBackground(new java.awt.Color(178, 178, 178));
        historico.setColumns(20);
        historico.setFont(new java.awt.Font("Cantarell", 1, 17)); // NOI18N
        historico.setForeground(new java.awt.Color(243, 243, 237));
        historico.setRows(5);
        historico.setText("    \n Partida     \t\n-----------------------------------\n Puntos  ");
        historico.setOpaque(false);
        getContentPane().add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 300, 90));

        sacar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        sacar.setText("Sacar Carta");
        sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarActionPerformed(evt);
            }
        });
        getContentPane().add(sacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 170, 40));

        marcador.setBackground(new java.awt.Color(175, 167, 160));
        marcador.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        marcador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcador.setText("Puntacion: 0 ");
        marcador.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(249, 252, 16)));
        marcador.setFocusable(false);
        marcador.setOpaque(true);
        getContentPane().add(marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 50));

        plantar.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        plantar.setText("Me Planto");
        plantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantarActionPerformed(evt);
            }
        });
        getContentPane().add(plantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 140, 40));

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 110, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/marron.jpg"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(800, 600));
        fondo.setMinimumSize(new java.awt.Dimension(800, 600));
        fondo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 900, 600));

        jMenu1.setText("Opciones");

        menuSacar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuSacar.setText("Sacar Carta");
        menuSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSacarActionPerformed(evt);
            }
        });
        jMenu1.add(menuSacar);

        menuMePlanto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuMePlanto.setText("Me Planto");
        menuMePlanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMePlantoActionPerformed(evt);
            }
        });
        jMenu1.add(menuMePlanto);

        menuReiniciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menuReiniciar.setText("Reiniciar");
        menuReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReiniciarActionPerformed(evt);
            }
        });
        jMenu1.add(menuReiniciar);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");

        acerca.setText("Acerca De.");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        jMenu2.add(acerca);

        instrucciones.setText("Instrucciones");
        instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instruccionesActionPerformed(evt);
            }
        });
        jMenu2.add(instrucciones);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarActionPerformed
        int palo, numero;
        contador++;
        //Saca una carta aleatoria y comprueba si ya ha salido
        do
        {
        palo = (int)(Math.random()*4);
        numero = (int)(Math.random()*10)+1;
        }while(!baraja.comprobarCarta(palo ,numero));
        
        baraja.sacarCarta(palo, numero);
        
        puntuacion = puntuacion + baraja.valorCarta(numero);
        marcador.setText("Puntuacion: "+String.valueOf(puntuacion));

        
        sacarCarta(contador,palo,numero);
        
        escribirSalida();
            
        if(contador==14)
        {
            terminarPartida();
            salida1.setText("Te has pasado");
        }
                
        
    }//GEN-LAST:event_sacarActionPerformed

    private void plantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantarActionPerformed
         if(puntuacion!=0)
         {
            terminarPartida();
         }
         else
         {
             JOptionPane.showMessageDialog(null,"No te puedes plantar sin sacar cartas");
         }
    }//GEN-LAST:event_plantarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        if(puntuacion!=0)
        {
            if(sacar.isEnabled())
                {
                    puntuacion=15;
                    terminarPartida();
                }
             iniciarPartida();
        }
        else
         {
             JOptionPane.showMessageDialog(null,"No puedes reiniciar la partida sin haber comenzado");
         }
    }//GEN-LAST:event_reiniciarActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        AcercaD da = new AcercaD(this,true);
        da.setVisible(true);
        da.setLocationRelativeTo(this);
    }//GEN-LAST:event_acercaActionPerformed

    private void menuSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSacarActionPerformed
        this.sacarActionPerformed(evt);
    }//GEN-LAST:event_menuSacarActionPerformed

    private void menuMePlantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMePlantoActionPerformed
        this.plantarActionPerformed(evt);
    }//GEN-LAST:event_menuMePlantoActionPerformed

    private void menuReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReiniciarActionPerformed
        this.reiniciarActionPerformed(evt);
    }//GEN-LAST:event_menuReiniciarActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
       System.exit(0);
       
       
    }//GEN-LAST:event_menuSalirActionPerformed

    private void instruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instruccionesActionPerformed
        Intrucciones ins = new Intrucciones(this,true);
        ins.setVisible(true);
        ins.setLocationRelativeTo(this);
    }//GEN-LAST:event_instruccionesActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    
        
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

      //Metodo que elige el jlabel donde pintar la carta y la pinta
    public void sacarCarta(int contador, int palo, int numero)
    {
        
        String carta = String.valueOf(numero);
        String resultado = "/imagenes/"+palo+"y"+carta+".png";
        
                switch(contador)
                {
                    
                    case 1: 
                    carta1.setVisible(true);    
                    carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 2: 
                    carta2.setVisible(true);      
                    carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 3: 
                    carta3.setVisible(true);      
                    carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 4: 
                    carta4.setVisible(true);      
                    carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 5: 
                    carta5.setVisible(true);      
                    carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 6:
                    carta6.setVisible(true);      
                    carta6.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 7:
                    carta7.setVisible(true);      
                    carta7.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 8:
                    carta8.setVisible(true);      
                    carta8.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 9:
                    carta9.setVisible(true);      
                    carta9.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 10:
                    carta10.setVisible(true);      
                    carta10.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 11:
                    carta11.setVisible(true);      
                    carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 12:
                    carta12.setVisible(true);      
                    carta12.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 13:
                    carta13.setVisible(true);      
                    carta13.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    case 14:
                    carta14.setVisible(true);      
                    carta14.setIcon(new javax.swing.ImageIcon(getClass().getResource(resultado)));
                    break;
                    default: 
                    carta1.setVisible(true);      
                    carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trasera.png")));
                    break;
                }
                
                        
    }
    private void escriturahistorico()
    {
       if(baraja.partida[0]!=0)
       {
           pto1.setText("  "+String.valueOf(baraja.partida[0])+"\n\n"+baraja.puntos[0]);
       }
       if(baraja.partida[1]!=0)
       {
           pto2.setText("  "+String.valueOf(baraja.partida[1])+"\n\n"+baraja.puntos[1]);
       }
       if(baraja.partida[2]!=0)
       {
           pto3.setText("  "+String.valueOf(baraja.partida[2])+"\n\n"+baraja.puntos[2]);
       }
       if(baraja.partida[3]!=0)
       {
           pto4.setText("  "+String.valueOf(baraja.partida[3])+"\n\n"+baraja.puntos[3]);
       }
       if(baraja.partida[4]!=0)
       {
           pto5.setText("  "+String.valueOf(baraja.partida[4])+"\n\n"+baraja.puntos[4]);
       }
        

    }
    
    //Cambia el texto de salida si consigues 7 y 1/2 o te pasas y llama a terminar partida            
    public void escribirSalida()
    {
        if(baraja.getPuntosB()==0)
        {
            if(puntuacion==7.5f)
            {
                salida1.setText("Enhorabuena 7y1/2");
                terminarPartida();
            }
            else
            {
                if(puntuacion>7.5f)
                {
                    salida1.setText("Te has pasado");
                    terminarPartida();
                }
            }
        }
        else
        {
            if(baraja.getPuntosB()==7.5f && puntuacion == 7.5f) 
            {
               salida1.setText("Enhorabuena 7y1/2\nPero Gana Jugador 2");       
            }
            else
            {
                if(baraja.getPuntosB()>7.5f)
                {
                    if(puntuacion==7.5f)
                    {
                        salida1.setText("Enhorabuena 7y1/2\n     Tu Ganas");
                    }
                    else
                    {
                    salida1.setText("Enhorabuena Tu Ganas");
                    }
                }
                else
                {
                    salida1.setText("Jugador 2 Gana");
                }
            }
        }    
      
    }
    
    //Acaba la partida
    private void terminarPartida()
    {
        baraja.setpuntosJ(puntuacion);
        baraja.reestructurarPuntos(puntuacion);
        escriturahistorico();
        sacar.setEnabled(false);
        plantar.setEnabled(false);
        menuSacar.setEnabled(false);
        menuMePlanto.setEnabled(false);
           
        if(puntuacion<=7.5f)
        {
            crearBanca();
            escribirSalida();
        }
    
            
    }
    //Inicia la partida
    private void iniciarPartida()
    {
        contador = 0;
        puntuacion = 0;
        salida1.setText("");
        marcador.setText("Puntuacion: "+String.valueOf(puntuacion));
        baraja.reiniciarBaraja();
        sacar.setEnabled(true);
        menuMePlanto.setEnabled(true);
        menuSacar.setEnabled(true);
        plantar.setEnabled(true);
        carta1.setVisible(false);
        carta2.setVisible(false);
        carta3.setVisible(false);
        carta4.setVisible(false);
        carta5.setVisible(false);
        carta6.setVisible(false);
        carta7.setVisible(false);
        carta8.setVisible(false);
        carta9.setVisible(false);
        carta10.setVisible(false);
        carta11.setVisible(false);
        carta12.setVisible(false);
        carta13.setVisible(false);
        carta14.setVisible(false);
        auxiliar=0;
        sw=true;
        
    }
    //    private void sacarBanca()
//    {
//       banca = new Banca1(VentanaPrincipal.this,true,VentanaPrincipal.this.puntuacion,baraja);
//       banca.setVisible(true);
//    }
    
//    private class Hilo1 extends Thread
//    {
//    @Override
//    public void run()
//            {
//        try {
//            while(sw)
//            {
//                switch(auxiliar)
//                {
//                    case 0:
//                        break;
//                    case 30:
//                        crearBanca();
//                        break;
//                    case 31:
//                        sw=false;
//                        break;
//                        
//                       
//                }
//                auxiliar++;
//                
//                
//            Thread.sleep(100);}
//           escribirSalida();
//        } catch (InterruptedException ex) {
//        Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
//        }
  

    
    public void crearBanca()
    {
       banca = new Banca1(VentanaPrincipal.this,true,VentanaPrincipal.this.puntuacion,baraja);
       banca.setVisible(true);
       banca.setLocationRelativeTo(null); 
    }
    public void cerrarBanca()
    {
       banca.dispose();
    }
 

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acerca;
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta10;
    private javax.swing.JLabel carta11;
    private javax.swing.JLabel carta12;
    private javax.swing.JLabel carta13;
    private javax.swing.JLabel carta14;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel carta3;
    private javax.swing.JLabel carta4;
    private javax.swing.JLabel carta5;
    private javax.swing.JLabel carta6;
    private javax.swing.JLabel carta7;
    private javax.swing.JLabel carta8;
    private javax.swing.JLabel carta9;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextArea historico;
    private javax.swing.JMenuItem instrucciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel marcador;
    private javax.swing.JMenuItem menuMePlanto;
    private javax.swing.JMenuItem menuReiniciar;
    private javax.swing.JMenuItem menuSacar;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JLabel oportunidad;
    private javax.swing.JButton plantar;
    private javax.swing.JTextArea pto1;
    private javax.swing.JTextArea pto2;
    private javax.swing.JTextArea pto3;
    private javax.swing.JTextArea pto4;
    private javax.swing.JTextArea pto5;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton sacar;
    private javax.swing.JLabel salida;
    private javax.swing.JTextArea salida1;
    private javax.swing.JLabel tapete;
    // End of variables declaration//GEN-END:variables
}

